---
title: "Comitê da Alta Gestão de Governança"
description: "Este Regimento tem por finalidade estabelecer os aspectos de organização e de funcionamento do Comitê da Alta Gestão de Governança, Desenvolvimento e Controles da Universidade Federal de Ciência e Inovação do Rio de Janeiro, UFCI/RJ."
author: Diego Carvalho
header: Pró-reitoria de Gestão Estratégica e Tecnologia da Informação
date: "06/18/2026"
format:
  clx-html: default
  clx-pdf:
    keep-tex: false
    classoption: [capitulo]
---


=capítulo Da finalidade

=artigo Este Regimento estabelece a organização e o funcionamento do Comitê da Alta Gestão de Governança da Universidade Federal de Ciência e Inovação do Rio de Janeiro (UFCI/RJ), em conformidade com:

=inciso Instrução Normativa Conjunta MP/CGU nº 01, de 10 de maio de 2016;

=inciso Decreto nº 9.203, de 22 de novembro de 2017;

=inciso Programa de Modernização do Poder Executivo Federal;

=inciso Estratégia de Governo Digital (EGD), instituída pelo Decreto nº 10.332, de 28 de abril de 2020;

=inciso Art. 5º da Portaria nº 19, de 29 de maio de 2017;

=inciso Diretrizes da Secretaria do Governo Digital, conforme Decreto nº 9.745, de 8 de abril de 2019; e

=inciso Decreto nº 12.198, de 24 de setembro de 2024, no que se refere às atribuições do Comitê de Governança Digital.

=capítulo Do Comitê da Alta Gestão de Governança

=artigo O Comitê da Alta Gestão de Governança (CAGG) é o órgão colegiado permanente de natureza deliberativa, de caráter estratégico e normativo, que tem como finalidade estabelecer políticas, diretrizes e a adoção de medidas para a sistematização de práticas relacionadas à governança, desenvolvimento digital, gestão de riscos e controles internos no âmbito da Universidade Federal de Ciência e Inovação do Rio de Janeiro, UFCI/RJ.

=capítulo Da composição e assessoramento

=artigo O Comitê da Alta Gestão de Governança é composto por:

=inciso Diretor-Geral;

=inciso Diretores Sistêmicos; e

=inciso Diretores dos campi.

=parágrafo O Comitê da Alta Gestão de Governança é presidido pelo Diretor-Geral.

=parágrafo Os membros têm direito a voz e voto.

=parágrafo Na ausência de qualquer membro, o ausente poderá ser representado pelo seu substituto eventual, que terá direito a voz e voto.

=artigo O Comitê da Alta Gestão de Governança é assessorado por:

=inciso Chefe do Departamento de Desenvolvimento Institucional;

=inciso Chefe do Departamento de Tecnologia da Informação; e

=inciso Encarregado do Tratamento de Dados Pessoais (DPO).

=parágrafo Os assesores têm direito a voz, mas não têm direito a voto.

=artigo A participação no CAGG será considerada prestação de serviço público relevante, não remunerada.

=artigo Incumbe à presidência do CAGG, ouvidos os demais membros deste comitê:

=inciso presidir as sessões e demais atividades do Comitê;

=inciso estabelecer calendário de reuniões ordinárias e convocar reuniões extraordinárias;

=inciso aprovar a pauta das reuniões;

=inciso decidir em caso de empate, utilizando o voto de qualidade;

=inciso autorizar a presença nas reuniões de pessoas que possam contribuir para os trabalhos do Comitê;

=inciso designar responsáveis ou grupo de trabalho para aprofundamento de estudo sobre assuntos técnicos e desenvolvimento de projetos especiais;

=inciso zelar pela Segurança da Informação na Instituição;

=inciso decidir as questões de ordem relativas à aplicação deste Regimento Interno;

=inciso expedir decisões, ad referendum, em vista de circunstâncias de urgência, normas complementares relativas ao seu funcionamento e à ordem dos trabalhos, bem como atos administrativos, ficando o tema obrigatoriamente inscrito na pauta da próxima reunião;

=inciso cumprir e fazer cumprir o Regimento Interno do Comitê.

=artigo São atribuições dos diretores sistêmicos e dos campi:

=inciso participar das reuniões ordinárias e extraordinárias do Comitê;

=inciso analisar, debater e votar as matérias em discussão, inclusive na condição de relator, se for o caso;

=inciso realizar estudos e pesquisas necessários ao desenvolvimento das atividades do comitê;

=inciso propor a designação de comissões ou grupos de trabalho para atuarem em caráter consultivo sobre os temas de governança e gestão de riscos em apoio à tomada de decisões do comitê;

=inciso propor a inclusão de matérias nas pautas das reuniões; e

=inciso participar de ações de capacitação relativas ao tema do Comitê.

=artigo São atribuições dos assessores do comitê:

=inciso prestar apoio nos assuntos relacionados à implementação e ao desenvolvimento da governança, implantação da gestão de riscos e controle e do desenvolvimento digital no âmbito institucional;

=inciso fazer a liaison com as respectivas comunidades;

=inciso presidir estudos demandados pela presidência para instruir as decisões do comitê; e

=inciso emitir pareceres sobre temas afetos às suas competências.

=capítulo Das competências

=artigo Compete ao CAGG:

=inciso auxiliar a administração na implementação e manutenção de processos, estruturas e mecanismos adequados à incorporação dos princípios e diretrizes da governança pública;

=inciso promover iniciativas que implementem o acompanhamento de resultados, promovam soluções para melhoria do desempenho institucional e aprimorem o processo decisório;

=inciso promover e acompanhar a implementação das medidas, mecanismos e práticas organizacionais de governança definidos pelo Comitê Interministerial de Governança (CIG);

=inciso promover práticas e princípios de conduta e padrões de comportamentos alinhados às melhores práticas de ética e integridade do serviço público;

=inciso institucionalizar estruturas adequadas de governança, gestão de riscos e controles internos;

=inciso promover o desenvolvimento contínuo dos agentes públicos e incentivar a adoção de boas práticas de governança, gestão de riscos e controles internos;

=inciso garantir a aderência às regulamentações, leis, códigos, normas e padrões na condução das políticas e prestação de serviços de interesse público;

=inciso articular a integração dos agentes responsáveis pela governança, gestão de riscos e controles internos;

=inciso institucionalizar a responsabilidade dos agentes públicos na prestação de contas, transparência e efetividade das informações;

=inciso aprovar políticas, diretrizes, metodologias e mecanismos para comunicação e institucionalização da gestão de riscos e controles internos;

=inciso supervisionar o mapeamento e avaliação dos riscos-chave que possam comprometer a prestação de serviços de interesse público;

=inciso liderar a institucionalização da gestão de riscos e controles internos, oferecendo suporte para sua efetiva implementação;

=inciso estabelecer limites de exposição a riscos globais, bem como limites de alçada ao nível de unidade, política pública ou atividade;

=inciso aprovar método de priorização de temas e macroprocessos para gerenciamento de riscos e implementação dos controles internos;

=inciso elaborar manifestações técnicas e emitir recomendações para o aprimoramento da governança, gestão de riscos e controles internos;

=inciso aprovar a política e diretrizes de Governança Digital e Gestão da Tecnologia da Informação do UFCI/RJ;

=inciso monitorar resultados e avaliar a gestão da Política de Governança e Gestão da Tecnologia da Informação em consonância com a legislação vigente;

=inciso aprovar as diretrizes do Plano Diretor de Tecnologia da Informação e Comunicação (PDTIC), suas revisões e avaliar sua execução;

=inciso aprovar o Plano de Transformação Digital (PTD);

=inciso aprovar o Plano de Dados Abertos (PDA);

=inciso deliberar sobre prioridades na formulação e execução de planos e projetos relacionados à Tecnologia da Informação e Comunicação, incluindo Serviços Públicos Digitais e Gestão de Riscos em Tecnologia da Informação;

=inciso avaliar os Sistemas de Informação do UFCI/RJ e propor atualizações, revisões e desativações;

=inciso deliberar sobre o Plano Anual de Contratações de soluções de Tecnologia da Informação e Comunicação;

=inciso aprovar, monitorar e avaliar as ações para adesão à Plataforma da Cidadania Digital e realizar interlocução com seu Comitê Gestor;

=inciso monitorar o cumprimento das recomendações do SISP e determinações do Governo Federal quanto aos projetos e ações de TIC; e

=inciso monitorar as recomendações e orientações deliberadas pelo Comitê.

=capítulo Das disposições gerais

=artigo O cronograma das reuniões ordinárias e suas respectivas atividades deverá ser divulgado na primeira sessão ordinária do exercício.

=artigo A implementação de todas as iniciativas relacionadas à governança, desenvolvimento digital, gestão de riscos e controles internos no âmbito do UFCI/RJ deverá ser submetida ao CAGG para conhecimento, análise e aprovação.

=artigo O regimento do Comitê poderá ser revisto mediante solicitação de, no mínimo, dois terços dos seus membros.

=artigo Os casos omissos serão resolvidos em votação pelos membros deste Comitê.

=artigo Este Regimento entrará em vigor após sua aprovação e homologação.
